### PR TITLE
Doc changes

### PR DESCRIPTION
**Pull request by gilv**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe what do you think?

**Comment by JosepSampe** [comment]
@gilv configuration in runtime is now repeated 2 times. is this correct? I'm not sure, but I'm not convinced of having an extra file for config.  Mabe it is all simple if we provide config file instructions at the top, then backends, then verify, and then alternative conig in runtime in only one file

**Comment by gilv** [comment]
@JosepSampe it's not repeated 2 times...but yes, i will remove the extra file for config

**Comment by gilv** [comment]
@JosepSampe how is it now?

**Comment by JosepSampe** [comment]
@gilv I see it much better, I was only not convinced of extra file. No more objections ;)

**Pull request merged**
