### PR TITLE
Improved lithops Monitoring & Invoker

### PR DESCRIPTION
**Pull request by JosepSampe**
- Refactor to improve lithops monitoring. Centrilized in a single entity the whole lithops job monitoring
- Abstracted wait and get_result methods. wait and get_result can be imported and called without having to create an executor
- Invoker refactor. Created 2 new invokers based on backend type and not on lithops mode
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe and it only 33 files you changed.. ;)

**Comment by gilv** [comment]
@JosepSampe i tried to test  this PR from the branch, got

```
  File "/Users/me/.pyenv/versions/3.8.5/bin/lithops", line 5, in <module>
    from lithops.scripts.cli import lithops_cli
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/lithops/__init__.py", line 1, in <module>
    from lithops.executors import FunctionExecutor
  File "/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/lithops/executors.py", line 31, in <module>
    from lithops.wait import wait, ALL_COMPLETED, THREADPOOL_SIZE, WAIT_DUR_SEC
ImportError: cannot import name 'wait' from 'lithops.wait' (/Users/me/.pyenv/versions/3.8.5/lib/python3.8/site-packages/lithops/wait/__init__.py)
```

**Comment by JosepSampe** [comment]
@gilv How did you test it? `wait` folder does not exist anymore, and seems you still have this folder

**Comment by gilv** [comment]
@JosepSampe I just did checkout of the PR with

    hub checkout https://github.com/lithops-cloud/lithops/pull/632
    pip install -U .
    build runtime...

**Pull request merged**
