### PR TITLE
Localhost Storage fixes/improvements

### PR DESCRIPTION
**Pull request by LachlanStuart**
* Support passing file-like objects to `put_object` for streaming uploads
    * The `1024*1024` parameter to `shutil.copyfileobj(data, f, 1024*1024)` determines chunk size. It may warrant further tuning, but I know that the default value (16kB) definitely causes performance issues.
* Support `head_bucket` and `head_object` functions
* Fixed empty parent directory deletion when deleting objects. The previous behavior was to delete a single parent directory, even if it was non-empty. Now it can delete multiple layers of empty directories, but only if they are actually empty.
* Made `list_keys`/`list_objects` behavior consistent with COS-style backends. 
    * Passing `prefix='foo'` will now match a files called `foo`, `foo0`, `foo123`, etc.
    * Changed `list_keys` to not use case-insensitive `glob`. I also changed `list_objects` to re-use `list_keys` so that their implementation doesn't diverge like this again.
    * Removed this code. I'm not sure what it was intended for, but it prevented `prefix='foo'` from matching `foo`.
        ```python
        if file_name.endswith(prefix):
            continue
        ```
* Added several tests to ensure Localhost and COS storage behavior was consistent
    * I found this test was broken before I even made any changes. I don't know what it does, so I haven't tried to fix it:
        ```
        ======================================================================
        FAIL: test_storage_handler (lithops.tests.TestLithops)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/home/lachlan/dev/lithops/lithops/tests.py", line 377, in test_storage_handler
            self.assertEqual(result, self.__class__.cos_result_to_compare)
        AssertionError: 291131 != 291130
        ----------------------------------------------------------------------
        ```

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by JosepSampe** [comment]
@LachlanStuart Regarding the test that fails, I ran all tests multiple times with the current master branch, and all them pass successfully in my case, so I wonder why this one fails for you. In my case I ran the tests both in Windows 10 (python 3.7) and Ubuntu 20.04 (Python 3.8)., what is your env?

**Comment by JosepSampe** [comment]
@LachlanStuart Can you fix the CHANGELOG.md file?

**Comment by LachlanStuart** [comment]
@JosepSampe I found the cause - one of my new tests adds another object that gets included in the word count. I'll make a new PR to delete extra files (other than the `test0`, etc. files) between each test.

**Comment by JosepSampe** [comment]
@LachlanStuart Yep, thanks, I found exactly the same now after running some tests.

**Comment by JosepSampe** [comment]
Maybe another solution, to prevent future similar issues, is to upload the dataset into `PREFIX/dataset` instead of in `PREFIX`, This way, all the files added by the storage tests won't interfere anymore in the other tests.

**Pull request merged**
