### PR TITLE
fix in partitioner

### PR DESCRIPTION
**Pull request by JosepSampe**
Fixed issue found in partitioner
Added execution_timeout parameter in config
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe what was the issue you found?

**Comment by JosepSampe** [comment]
fact1: When you have to process objects from a bucket, if you don't provide `chunk_size`, lithops spawns one function for each object in the bucket. 

fact2 When the object processing feature is activated, from within a function you can access the size of the chunk with:

```python
def analyze_comments(obj):
    print(obj.chunk_size)
```

In case of fact1, `obj.chunk_size` was always `None`. With this patch, in case of fact1, `obj.chunk_size` is the whole size of the object.

**Comment by gilv** [comment]
@JosepSampe merge it when you done..thanks

**Comment by JosepSampe** [comment]
@gilv ok

**Pull request merged**
