### PR TITLE
[storage] support for globber and modifications to the partitioner

### PR DESCRIPTION
**Pull request by gilv**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe here we go

- there was a bug, when url contains object_names but list performed on the bucket level. This resulted in huge list returned, while ignored by key_dict. I fixed this, and perform HEAD instead of list
- removed some duplicated lists. Now we split objects directly from the main loop, instead of looping twice
- added support for slobber, now Lithops can support URLs of the forms `/*/ab*/mydata`, etc.

**Comment by gilv** [comment]
@JosepSampe any concerns?

**Review by JosepSampe — COMMENTED** [review]
Not for now, I think it is ok

**Comment by gilv** [comment]
@JosepSampe then good luck for us ;) I merge it.. I also think it's ok. `lithops verify` pass with this PR

**Pull request merged**
