### PR TITLE
Separate serverless logic from serverfull logic

### PR DESCRIPTION
**Pull request by JosepSampe**
Code refactor that separates serverless logic from standalone logic.

With recent integration of IBM VPC as standalone mode of execution it makes necessary to separate the serverless logic from the serverfull, since each one has its own particular characteristics. Use serverelss logic to invoke standalone jobs only adds overheads., so now each mode of execution has its own invoker.

Changes in the standalone mode:
- Reduced the time needed to detect that the VM is running from 95 seconds to 70 seconds.
- The proxy is installed as a unix service in the VM. Instead of running it in the Docker runtime as it was in the previous approach
- The proxy is automatically started when the VM starts. If the proxy fails for some reason, the OS is responsible to reexecute it automatically.
- The VM can now run jobs in docker images or in the default VM python3 interpreter
- Now it is possible to run more than 1 different docker runtime in the VM
- Now the Docker package is automatically  installed the first time a lithops script is executed. The users no need anymore to manually access to the VM and install it.

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe there is 109 files changed...any way you manage to submit smaller PRs instead of  a huge one? I even don't know where to start from with 109 changed files... I assume this PR contains various fixes / additions that are not related each other, no?

**Comment by JosepSampe** [comment]
@gilv Most of them are code movement from "compute/backends" to "serverless/backends", and some minor changes in all config docs. Now it is impossible to split it in multiple PRs. There are only 5 new files that you can easily see ;)

**Comment by gilv** [comment]
@JosepSampe are there some changes to Gen2 VMs section?

**Comment by JosepSampe** [comment]
@gilv In Gen2 VM itself no, the code to start/stop IBM VPCs VMs is the same. What is changed is the proxy that is executed within the VM.

**Comment by gilv** [comment]
@JosepSampe is this PR related #361 and #362 ? if yes, how?

**Comment by JosepSampe** [comment]
Yes to #362, no to #361. It is explained in the first post ;)

**Comment by gilv** [comment]
@JosepSampe i just not sure where to start with ;) 109 files is a bit too much for a single PR...

**Comment by gilv** [comment]
@JosepSampe so we used docker_executor with conf

```

compute_backend: docker
remote_client: ibm_vpc

...
docker:
    host: IP
    ssh_user: user
    ssh_key_filename: 

ibm_vpc:
    endpoint: https://us-south.iaas.cloud.ibm.com
    instance_id: some id
```

With new changes how this will look like?

**Comment by JosepSampe** [comment]
Docker executor is not used anymore. You only need these keys in config:

```yaml
lithops:
    executor: standalone

ibm_vpc:
    endpoint: <endpoint>
    instance_id: <instance-id>
    ip_address: <floating-ip-address>
```

**Comment by gilv** [comment]
@JosepSampe i used Docker executor to deploy workloads to my regular VM, not Gen2.
It worked for me only with this
```
docker:
    host: IP
    ssh_user: me
    ssh_password: aha
```

But seems with your change it will not work anymore?

**Comment by gilv** [comment]
@JosepSampe by we "we can add this" you mean there is need to add more code to support this? or with current code

```
vm:
    ip_address: <ip>
    ssh_user: <user>
    ssh_password: <pass>
and

lithops.StandaloneExecutor(backend=vm)
```

This will already works?

**Comment by JosepSampe** [comment]
@gilv Now yes ;) With this refactor it is pretty easy to add standalone backends

**Comment by gilv** [comment]
@JosepSampe any chance you can split this PR into at least 2? One PR to handle only serverless compute changes:cf, lambda, azure, etc...second one will change the VM / Docker / etc. related parts? And 3rd one with documentation?

**Comment by JosepSampe** [comment]
@gilv uff.. I can't split it now, it contains alot of changes with alot of commits. It will take me one week of more work, and at the end it will contain the same changed files.. I think you can easily see what are docs and what is code. You can directly check my branch if it is easy for you to see the changes

**Comment by gilv** [comment]
@JosepSampe yeah...i know it's a lot of changes and commits ;) Leave it as is...but be aware it will take some  time to test it and such PR is sort of a blocker..since nothing else can be merged before this one.

**Comment by gilv** [comment]
@JosepSampe please don't push changes in this PR anymore, let me review it. If you need another commit, please summarise what it does. Otherwise i can't follow this if there are new commits lands here

**Comment by gilv** [comment]
@JosepSampe so with this PR we have:
1. all existing FaaS backends, like cf_executor, aws_executor, etc, will use ServerlessExecutor internally
2. local_executor that uses LocalHost executor internally
3. function_executor that use FunctionExecutor internally.

Why we need 3? Why function_executor doesn't use ServerlessExecutor?
Why you decided that docker_executor will be merged with local_executor?

**Comment by JosepSampe** [comment]
@gilv It is all easy to understand if you think that now lithops supports 3 modes of execution: **localhost**, **serverless** and **standalone**. Each mode of execution has its own Executor with its own parameters. Form example, servelss executor has `runtime_memory ` parameter, while StandaloneExecutor has `cpu`, `memory`, `instances`, `etc` parameters, while LocalhostExecutor has none of them. 
This way, in your scripts you can differentiate what is executed in serverless, in a VM or in localhost:

```python
...
fexec = lithops.ServrelessExecutor()
...
fexec = lithops.StandaloneExecutor()
...
fexec = lithops.LocalhostExecutor()
...
```

Then we have another executor called **FunctionExecutor**. The FunctionExecutor is a top-level executor that engloves the localhost, servereless and standalone executors. So instead of using in your scripts the low-level executors stated before, you can use everywhere the FunctionExecutor and then decide in config if they are serverless, localhost or standalone. For example:
```python
...
fexec = lithops.FunctionExecutor(type='serverless') #type param is loaded from config file if not provided
...
fexec = lithops.FunctionExecutor('type='localhost')
...
fexec = lithops.FunctionExecutor(type='standalone')
...
```

-----------------

Docker backend and Local backend was merged into the new **Localhost mode of execution** because in fact docker and localhost were not compute backends, but **execution environaments**. This reduced alot the complexity of the code. Now you can use `fexec = lithops.LocalhostExecutor()` to run function in your default `python3` interpreter, and also in a docker image by simply specifying a docker runtime` fexec = lithops.LocalhostExecutor(runtime='jsampe/lithops-py3.6')`. With this, in the future we can also support virtualenvs packaged into a zip file, so the user could specify something like this to run functions within a packaged viertualenv: `fexec = lithops.LocalhostExecutor(runtime='my-lithops-env-py36.zip')`

-----------------

LocalhostExecutor is only localhost executor and can only run local jobs. Anything remote like a regular VM is StandaloneExecutor(), which includes all the ssh logic needed to interact with the VM.

-----------------

All of this will be properly documented, but for now I don't want to modify any other file ;)

**Comment by gilv** [comment]
@JosepSampe i want to merge it ( seems i got brave enough). Can you please just adapt branch to the changes in master? I will then give it few tests and merge it

**Comment by JosepSampe** [comment]
@gilv Done

**Comment by JosepSampe** [comment]
@gilv Done!

**Comment by JosepSampe** [comment]
@gilv Done!

**Comment by gilv** [comment]
@JosepSampe I will merge and we then start testing it..i guess many things will be broken initially. 
may the force be with us :)

**Comment by JosepSampe** [comment]
@gilv From my side All tests passed with IBM CF and IBM VPC ;)

**Pull request merged**
