### PR TITLE
Provide ability to automatically create and delete VM instances

### PR DESCRIPTION
**Pull request by kpavel**
* New StandaloneExecutor create() API added to provision new temporary VM in IBM VPC
* New delete_on_dismantle boolean flag added under config ibm_vpc section. In case True, the VM instance deleted instead of stopped by default
* Used ibm_vpc python SDK instead. We should consider to change the start/stop to use sdk as well
 
usage example:
```
import lithops

def hello(name):
    print("in hello")
    return 'Hello {}!'.format(name)

if __name__ == '__main__':
  fexec = lithops.StandaloneExecutor(log_level='DEBUG')

  fexec.create()  #provisions vm instance in ibm vpc

  fexec.call_async(hello, 'Worlds')
  print(fexec.get_result())
```

A number of new parameters required under ibm_vpc section in order to provision VMs in IBM VPC:
* security_group_id: <SECURITY_GROUP_ID>
* subnet_id: <SUBNET_ID>
* key_id: <PUBLIC_KEY_ID>
* resource_group_id: <RESOURCE_GROUP_ID>
* vpc_id: <VPC_ID>
* image_id: <IMAGE_ID>
* zone_name: <ZONE_NAME>
* volume_tier_name: <VOLUME_TIER_NAME>  # Optional, 10iops-tier by default
* profile_name: <PROFILE_NAME>  # Optional, bx2-8x32 by default

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@kpavel thanks a lot ...let me review it

**Comment by JosepSampe** [comment]
Awesome addition! @kpavel could you update the IBM VPC doc file as well?
https://github.com/lithops-cloud/lithops/blob/master/config/compute/ibm_vpc.md

It should contain, for example, another configuration option like [here](https://github.com/lithops-cloud/lithops/blob/master/config/compute/ibm_cf.md#configuration). And also the last table should contain the new keys and where to obtain them.

**Comment by kpavel** [comment]
@JosepSampe Done

**Comment by gilv** [comment]
@kpavel @JosepSampe this is ongoing work and other changes need to be added. I will merge this PR, it affects only IBM VPC and doesn't has effect on the other backends. We will continue testing this extension from the master branch

**Pull request merged**
