### PR TITLE
Lithops code engine

### PR DESCRIPTION
**Pull request by gilv**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe i got sick of using separate branch. As you can see 99.99% of the changes in the code_engine backend. few minor changes in the core components, which we can improve at later stage.

**Comment by gilv** [comment]
#377

**Comment by gilv** [comment]
This is initial JOB API of Code Engine. What is missing:
1. support for array jobs of index > 1
2. create job definition per map job and then delete job definition once map completed ( instead delete jobs one by one )
3. support for cases where job definition was deleted outside of Lithops

**Comment by gilv** [comment]
@JosepSampe if there is no objections from your side within 30 min from now - i will merge it ;)

**Comment by JosepSampe** [comment]
@gilv go ahead ;)

**Pull request merged**
