### PR TITLE
Fixed expired IAM token in IBM CF during an execution

### PR DESCRIPTION
**Pull request by JosepSampe**
- Request a new token in IBM CF when it expires during an execution #485 
- Fix in localhost Storage API
- Fix in code engine #489 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe wow...you are fast :) can we merge it and test ?

**Comment by JosepSampe** [comment]
@gilv Now yes ;)

**Comment by gilv** [comment]
@JosepSampe do we also need a stub clean for Standalone executor? Otherwise same code work for CE but print nasty exception for Standalone

```
   run_test("standalone", "ibm_vpc", cf_runtime)
  File "/Users/gilv/Dev/ibm-pywren-internal/pywren-tester/pywrencos/PyWrenColigoTest2.py", line 19, in run_test
    pw.compute_handler.clear()
AttributeError: 'StandaloneHandler' object has no attribute 'clear'
```

**Comment by JosepSampe** [comment]
@gilv Done

**Pull request merged**
