### PR TITLE
New Testing Framework

### PR DESCRIPTION
**Pull request by Cohen-J-Omer**
@gilv @erezh16 @JosepSampe 
In this PR: 
- Modified and expended the local testing system. 
Please refer to testing.md for more details.
- Git-action implementation:
 --[Warning] do not merge before disabling git-actions via repository settings-> actions. The git-actions are bound to fail without going through the complete process needed to configure the repository and the accounts:  
 --[Warning] this merge will not be effective unless a designated IBM-cloud (with configured CE, CF and COS) and docker-hub accounts are created. more info regarding the above is available in an internal documentation.  
 --Tests will automatically run against each pull request before a merge can take place (upon their success).
 --Said tests will run on git-hubs' VM's, on multiple configurations, simultaneously. 
 --Currently the testing procedure is configured to run on CE, CF, COS and local-host.
 --Due to current instability issues, the testing procedure doesn't run on CE.
 --Commenting out a configuration in .github/workflows/jobs_to_run.txt will allow the testing procedure to skip said configuration, 
 thus, still allowing a merge to occur.

 

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by gilv** [comment]
@JosepSampe we about to merge it...

**Comment by gilv** [comment]
@JosepSampe any objections? concerns?

**Comment by gilv** [comment]
@JosepSampe what 'verify' did before?

**Comment by JosepSampe** [comment]
@gilv before, `lithops test` ran a simple call_async, and `lithops verify` ran the full suite of tests

**Comment by erezh16** [comment]
@JosepSampe you can always run any single test via the new `lithops test`. If you want to run a particular test upon deployment, we just need to adjust the documentation for that.

**Comment by Cohen-J-Omer** [comment]
Hey @JosepSampe, I appreciate the feedback. 

My experience as a new user of lithops has led me to the understanding, that practically hiding the full array of tests from users could hurt the project's reputation. I'll explain with an example:

Imagine installing lithops, making a few configuration mistakes trying to follow documentations, receiving the: "Lithops is working as expected :)" confirmation from running "lithops test", and then encountering errors from trying to run a, lets say, storage based operation (or any other operation that isn't directly related to async). 

What comes to said user's mind is the impression that the project isn't reliable and is poorly tested, since he already received a confirmation promising that he has done everything well. Even with a moderate sized user base you'll be swamped with confident users opening issues, asking you to fix the project, stating that they received the "A-OK", not knowing that had they ran "lithops verify", it would fail.

**Comment by JosepSampe** [comment]
@Cohen-J-Omer From my point of view, I can't agree with you for some reasons ;)
>Imagine installing lithops, making a few configuration mistakes trying to follow documentations, receiving the: "Lithops is working as expected :)" confirmation from running "lithops test" and then encountering errors from trying to run a, lets say, storage based operation (or any other operation that isn't directly related to async).
- If a user makes configuration mistakes, nothing will work.
- Full suite of tests was never hidden, it was always under` lithops verify`.
- A simple and fast `lithops test` that runs a call_async()  with "Lithops is working as expected :)" uses the main internal Lithops components, even the compute and storage backends. So if the config is ok, and this command runs ok, you are ready to use lithops. This functionality is inherited from [pywren](http://pywren.io/pages/gettingstarted.html) that has a similar command.
- I have to manage every year 80+ new Lithops users and all them can work with lithops once `lithops test` "call_async" works. None of them had to run the full unit testing.

>What comes to said user's mind is the impression that the project isn't reliable and is poorly tested, since he already received a confirmation promising that he has done everything well. Even with a moderate sized user base you'll be swamped with confident users opening issues, asking you to fix the project, stating that they received the "A-OK", not knowing that had they run "lithops verify", it would fail.
- In fact I agree that sometimes the project is poorly tested. But as far as I understand, this PR will be used to run this full suite of tests automatically and simplify the development, adding another layer of verification in case a developer missed/forgot to run the tests.
- If a users finds an issue, he will open an issue in github, either he runs the full test suite or not.
- There will be always issues, even running the full suite of tests, so a user can run `lithops test`, receive A-OK, then run `lithops verify`, receive A-OK, and then find a mysterious exception somewhere.

So, for common users, 99% of times a call to `lithops test` (`call_async`) is enough to verify the config is ok and lithops works as expected, since `call_async` uses 95% of the main internal components. So a user can immediately use lithops with a user-friendly, simple and fast  `lithops test` command.
For developers, it mus be mandatory to run the full suite of tests and ensure that any change made in the code runs ok. This PR will help on this process. In [CONTRIBUTING](https://github.com/lithops-cloud/lithops/blob/master/CONTRIBUTING.md) file, it is already specified all the steps a developer must do.

But as I said, it is only my point of view ;)

**Comment by Cohen-J-Omer** [comment]
Since lithops stores intermediate computations in the cloud, I agree, even tests running on local datasets will test the functionality of the configured storage. 
But I genuinely wonder:
1. How sure are you of that 95% coverage mentioned? Does an async type test, also covers a map / map_reduce / all kinds of storage tests?  
2. Are you sure this "async reliance" is future proof? i.e., will new tests, testing new features of lithops, will be covered by a given async test? 

I'm sure we're all trusting your judgment in the matter @JosepSampe. If needed I'll gladly make the necessary adjustments.

**Comment by JosepSampe** [comment]
> How sure are you of that 95% coverage mentioned? Does an async type test, also covers a map / map_reduce / all kinds of storage tests?

Yes; call_async, map_ and map_reduce are top-level interfaces of the same underlying code. And yes, a lithops job needs to put/get/list/post data to/from the storage backend. So this covers 90 - 95 % of the main internal workflow. The things that are not covered in a simple call_async are more those advanced lithops features, like the storage partitioner.

> Are you sure this "async reliance" is future proof? i.e., will new tests, testing new features of lithops, will be covered by a given async test?

From my point of view, a common user might not need to test all the lithops features. I think the intention is to have a simple command that validates the config and the main lithops workflow in an easy and quick way. We, as a developers, must ensure that all these (new) features works ok when integrated in lithops.

**Comment by Cohen-J-Omer** [comment]
No problem @JosepSampe, I'll issue a new commit once I've tested the changes don't break anything. 
I'll make sure the documentation are updated as well (i.e. test <-> verify).

**Comment by Cohen-J-Omer** [comment]
@gilv @erezh16 @JosepSampe 
Problem found:

- After a lot of trial and error I've figured out that nothing was broken in comparison to lithops' source repository. 
The error lies within a race condition - both CE and CF relied on the same bucket when running in parallel on different GitHub VMs (GitHub jobs). 

Solution provided on the latest commit: 

- Created a dedicated bucket for Code-Engine (within the same account).  

An important conclusion to keep in mind: 

- Although the jobs (VM's) running the different lithops configurations can run in parallel, running more than one pull request at a time might very well cause a race condition on storage, because not only the same buckets will simultaneously serve multiple operations (reading/writing), but from this commit forwards, every Github job will begin with running the command "lithops clean".

**Comment by JosepSampe** [comment]
@Cohen-J-Omer So, is this PR ready? I'm new with these kind of testing, so I have some questions: How theses tests are executed? They use github resources? which config file they use?

**Comment by testing-alt** [comment]
Hey @JosepSampe, yes, the PR is ready as far as i'm concerned. 
I set each compute-storage backend combination to run in parallel as a different job. 
Each github job runs on an isolated VM which get wiped clean once it's done running.
Currently, the automatic testing part of the PR isn't usable since the config files i'm filling during runtime are pointing to my own accounts. 
Once we'll get allocated ibm cloud accounts, i could modify the settings in the repository and given accounts to integrate them into the github actions framework.

Have a great day!

**Pull request merged**
